<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MVVrus.AspNetCore.ActiveSession">
      <HintPath>..\..\ActiveSession\MVVrus.AspNetCore.ActiveSession\bin\Debug\net6.0\MVVrus.AspNetCore.ActiveSession.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
